config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: redirect(Setting.where(key: "homepage").first.value)
  mount Ckeditor::Engine => '/ckeditor'

  resources :categories, only: [:show]
  resources :pages, only: [:show]

  namespace :admin do
    resources :types, except: [:show]
    resources :menus, except: [:show]
    resources :pages # /admin/pages
    resources :categories
    get "settings" => "settings#index"
    put "settings" => "settings#update"
  end

  Page.where.not("slug", nil).all.each do |page|
    get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :pages
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/field.rb
class Field < ActiveRecord::Base
  belongs_to :page
  belongs_to :field_definition
end

app/models/field_definition.rb
class FieldDefinition < ActiveRecord::Base
  belongs_to :type
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates_presence_of :name
  has_many :menu_items

  accepts_nested_attributes_for :menu_items, reject_if: :all_blank
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :category
  belongs_to :type

  has_many :fields

  accepts_nested_attributes_for :fields, reject_if: :all_blank

  # page.url
  def method_missing name, *args, &block
    field = self.fields.find { |field| field.field_definition.key == name.to_s }
    if field
      field.value
    else
      super
    end
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :field_definitions

  accepts_nested_attributes_for :field_definitions, reject_if: :all_blank
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ContentController
  def show
    @category = Category.includes(:pages).find params[:id]

    render template: "category"
  end

  protected

  def template_to_render
    if template_exists?("category-#{@category.id}")
      "category-#{@category.id}"
    else
      "category"
    end
  end
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  before_filter :set_theme
  before_filter :retrieve_menus

  def set_theme
    theme = Setting.where(key: "theme").first.value
    prepend_view_path "app/themes/#{theme}"
    self.class.layout "../../themes/#{theme}/layout"
  end

  def retrieve_menus
    @menus = Menu.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ContentController
  def show
    @page = Page.find params[:id]

    render template: template_to_render
  end

  protected

  def template_to_render
    if template_exists?("page-#{@page.id}")
      "page-#{@page.id}"
    elsif template_exists? "page-#{@page.type.name}"
      "page-#{@page.type.name}"
    else
      "page"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_page page
    path = if page.slug.present?
      page.slug
    else
      "pages/#{page.id}"
    end

    root_path + path
  end

  def url_for_menu_item menu_item
    if menu_item.url.match /:\/\// # http://, ftp://, etc.
      menu_item.url
    else
      root_path + menu_item.url
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/admin/pages/_form.html.haml
= form_for [ "admin", @page ] do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :title
    = f.text_field :title, class: "form-control"

  %h3 Custom fields

  =f.fields_for :fields do |c|
    %p
      =c.label :value, c.object.field_definition.key
      =c.text_field :value, class: "form-control"
      =c.hidden_field :field_definition_id

  %p
    = f.label :body
    = f.cktext_area :body
  %p
    = f.label :slug
    = f.text_field :slug, class: "form-control"
  %p
    =f.label :category_id
    =f.select :category_id, Category.all.map { |category| [ category.name, category.id] }, class: "form-control"
  %p
    =f.hidden_field :type_id
    = f.submit 'Save'

app/views/admin/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', admin_page_path(@page)
\|
= link_to 'Back', admin_pages_path

app/views/admin/pages/index.html.haml
%h1 All Pages

%table.table
  %thead
    %tr
      %th Title
      %th Body
      %th Slug
      %th

  %tbody
    - @pages.each do |page|
      %tr
        %td= link_to page.title, edit_admin_page_path(page)
        %td= truncate page.body, length: 100
        %td
          %code=url_for_page page
        %td
          =link_to 'Destroy', admin_page_path(page), :method => :delete, :data => { :confirm => 'Are you sure?' }

%p
  = link_to 'New Page', new_admin_page_path, class: "btn btn-primary"
  -Type.all.each do |type|
    = link_to "New #{type.name}", new_admin_page_path(type: type.name), class: "btn btn-default"

app/views/admin/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', admin_pages_path

app/views/admin/pages/show.html.haml
%h1= @page.title

= simple_format @page.body

= link_to 'Edit', edit_admin_page_path(@page)
\|
= link_to 'Back', admin_pages_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(charset='utf-8')
    %title Tuts+ CMS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    =render "admin_nav"
    .container
      =content_tag :div, notice, class: "flash bg-success" if notice
      =content_tag :div, alert, class: "flash bg-danger" if alert
      = yield

app/views/pages/show.html.haml
%h1= @page.title

%p
  %em=time_ago_in_words @page.created_at

%dl
  -@page.fields.each do |field|
    %dt=field.field_definition.key
    %dd=field.value

= simple_format @page.body